name: Test
on:
  workflow_call:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  pull_request:
  schedule:
    # monthly https://crontab.guru/#0_0_10_*_*
    - cron: "0 0 10 * *"
  workflow_dispatch:

permissions: {}
jobs:
  test:
    uses: bats-core/.github/.github/workflows/test.yml@main
    permissions:
      contents: read
      security-events: write
      id-token: write
